import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Upload, FileText, Sparkles, ChevronLeft, ChevronRight, RotateCw } from "lucide-react";

export default function AIFlashcards() {
  const [currentCard, setCurrentCard] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  // Mock data - will be generated by Django + AI API
  const flashcardSets = [
    { id: 1, title: "Calculus Derivatives", cards: 15, subject: "Mathematics", lastStudied: "2 days ago" },
    { id: 2, title: "Quantum Physics Basics", cards: 20, subject: "Physics", lastStudied: "1 week ago" },
    { id: 3, title: "Organic Chemistry Reactions", cards: 12, subject: "Chemistry", lastStudied: "3 days ago" },
  ];

  const sampleFlashcards = [
    { 
      front: "What is the derivative of x²?", 
      back: "The derivative of x² is 2x, using the power rule: d/dx(xⁿ) = nxⁿ⁻¹" 
    },
    { 
      front: "Define Newton's Second Law", 
      back: "F = ma. The force acting on an object is equal to the mass of that object times its acceleration." 
    },
    { 
      front: "What is the molecular formula of glucose?", 
      back: "C₆H₁₂O₆ - Glucose is a simple sugar and important energy source in living organisms." 
    },
  ];

  const handleNext = () => {
    setCurrentCard((prev) => (prev + 1) % sampleFlashcards.length);
    setIsFlipped(false);
  };

  const handlePrevious = () => {
    setCurrentCard((prev) => (prev - 1 + sampleFlashcards.length) % sampleFlashcards.length);
    setIsFlipped(false);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-foreground">AI Flashcards</h1>
        <p className="text-muted-foreground mt-1">Generate smart flashcards from your study materials</p>
      </div>

      {/* Upload Section */}
      <Card className="border-border border-dashed border-2 bg-muted/50">
        <CardContent className="pt-6">
          <div className="flex flex-col items-center justify-center py-8 text-center">
            <div className="h-16 w-16 rounded-full bg-primary/10 flex items-center justify-center mb-4">
              <Upload className="h-8 w-8 text-primary" />
            </div>
            <h3 className="text-lg font-semibold text-foreground mb-2">Upload Study Material</h3>
            <p className="text-sm text-muted-foreground mb-4 max-w-md">
              Upload PDF, images, or documents. Our AI will analyze and create flashcards automatically.
            </p>
            <Button className="bg-primary hover:bg-primary-dark text-primary-foreground">
              <FileText className="h-4 w-4 mr-2" />
              Choose Files
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Flashcard Sets */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" />
          <h2 className="text-2xl font-bold text-foreground">Your Flashcard Sets</h2>
        </div>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {flashcardSets.map((set) => (
            <Card key={set.id} className="border-border hover:shadow-md transition-shadow">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="text-foreground">{set.title}</CardTitle>
                    <CardDescription>{set.subject}</CardDescription>
                  </div>
                  <Badge variant="secondary" className="bg-primary/10 text-primary">
                    {set.cards} cards
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-sm text-muted-foreground">Last studied: {set.lastStudied}</p>
                <Button 
                  variant="outline" 
                  className="w-full border-primary text-primary hover:bg-primary hover:text-primary-foreground"
                >
                  Study Now
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Flashcard Viewer */}
      <div className="space-y-4">
        <h2 className="text-2xl font-bold text-foreground">Practice Mode</h2>
        <Card className="border-border">
          <CardContent className="p-8">
            <div className="space-y-6">
              {/* Flashcard */}
              <div 
                className="relative min-h-[300px] rounded-lg bg-gradient-primary p-8 cursor-pointer shadow-lg hover:shadow-xl transition-shadow"
                onClick={() => setIsFlipped(!isFlipped)}
              >
                <div className="absolute top-4 right-4">
                  <Badge className="bg-white/20 text-white">
                    {currentCard + 1} / {sampleFlashcards.length}
                  </Badge>
                </div>
                <div className="flex items-center justify-center min-h-[250px]">
                  <div className="text-center">
                    <p className="text-sm font-medium text-white/80 mb-4">
                      {isFlipped ? "Answer" : "Question"}
                    </p>
                    <p className="text-xl font-semibold text-white">
                      {isFlipped 
                        ? sampleFlashcards[currentCard].back 
                        : sampleFlashcards[currentCard].front
                      }
                    </p>
                  </div>
                </div>
                <div className="absolute bottom-4 right-4">
                  <RotateCw className="h-5 w-5 text-white/60" />
                </div>
              </div>

              {/* Controls */}
              <div className="flex items-center justify-between">
                <Button
                  variant="outline"
                  onClick={handlePrevious}
                  className="border-primary text-primary hover:bg-primary hover:text-primary-foreground"
                >
                  <ChevronLeft className="h-4 w-4 mr-2" />
                  Previous
                </Button>
                <Button
                  onClick={() => setIsFlipped(!isFlipped)}
                  className="bg-primary hover:bg-primary-dark text-primary-foreground"
                >
                  <RotateCw className="h-4 w-4 mr-2" />
                  Flip Card
                </Button>
                <Button
                  variant="outline"
                  onClick={handleNext}
                  className="border-primary text-primary hover:bg-primary hover:text-primary-foreground"
                >
                  Next
                  <ChevronRight className="h-4 w-4 ml-2" />
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
