import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Brain, Upload } from "lucide-react";

export default function AIQuiz() {
  const navigate = useNavigate();

  // Mock data - will be generated by Django + AI API
  const quizSets = [
    { id: 1, title: "Calculus Final Prep", questions: 25, subject: "Mathematics", difficulty: "Hard" },
    { id: 2, title: "Physics Fundamentals", questions: 20, subject: "Physics", difficulty: "Medium" },
    { id: 3, title: "Chemistry Quick Review", questions: 15, subject: "Chemistry", difficulty: "Easy" },
  ];

  const handleStartQuiz = (quizId) => {
    navigate(`/quiz/take/${quizId}`);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-foreground">AI Quiz Generator</h1>
        <p className="text-muted-foreground mt-1">Test your knowledge with AI-generated quizzes</p>
      </div>

      {/* Upload Section */}
      <Card className="border-border border-dashed border-2 bg-muted/50">
        <CardContent className="pt-6">
          <div className="flex flex-col items-center justify-center py-8 text-center">
            <div className="h-16 w-16 rounded-full bg-primary/10 flex items-center justify-center mb-4">
              <Upload className="h-8 w-8 text-primary" />
            </div>
            <h3 className="text-lg font-semibold text-foreground mb-2">Generate New Quiz</h3>
            <p className="text-sm text-muted-foreground mb-4 max-w-md">
              Upload study materials and let AI create customized quizzes for you
            </p>
            <Button className="bg-primary hover:bg-primary-dark text-primary-foreground">
              <Brain className="h-4 w-4 mr-2" />
              Create Quiz
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Quiz Sets */}
      <div className="space-y-4">
        <h2 className="text-2xl font-bold text-foreground">Available Quizzes</h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {quizSets.map((quiz) => (
            <Card key={quiz.id} className="border-border hover:shadow-md transition-shadow">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="text-foreground">{quiz.title}</CardTitle>
                    <CardDescription>{quiz.subject}</CardDescription>
                  </div>
                  <Badge 
                    variant="secondary"
                    className={
                      quiz.difficulty === "Easy" ? "bg-success/10 text-success" :
                      quiz.difficulty === "Medium" ? "bg-warning/10 text-warning" :
                      "bg-destructive/10 text-destructive"
                    }
                  >
                    {quiz.difficulty}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-sm text-muted-foreground">{quiz.questions} questions</p>
                <Button 
                  onClick={() => handleStartQuiz(quiz.id)}
                  className="w-full bg-primary hover:bg-primary-dark text-primary-foreground"
                >
                  Start Quiz
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
