# Generated by Django 5.2.8 on 2026-01-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_studymaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="capacity",
            field=models.IntegerField(default=50),
        ),
    ]
