# Generated by Django 5.2.8 on 2026-02-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_useractivity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizresult",
            old_name="taken_at",
            new_name="date_taken",
        ),
        migrations.AddField(
            model_name="quizresult",
            name="topic",
            field=models.CharField(default="General", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizresult",
            name="total_questions",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="score",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="study_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.studygroup",
            ),
        ),
    ]
