# Generated by Django 5.2.8 on 2026-02-21 13:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0007_rename_taken_at_quizresult_date_taken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("quiz_data", models.JSONField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField(default=datetime.timedelta(days=7))),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.studygroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quizresult",
            name="AssignedQuiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groups.assignedquiz",
            ),
        ),
    ]
