# Generated by Django 5.2.8 on 2026-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_topic_question_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hidden_test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
