# Generated by Django 5.2.8 on 2026-06-02 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_question_hidden_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_practiced',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
