# Generated by Django 5.2.8 on 2026-06-02 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_userprogress_last_practiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='has_coding_portal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
