# Generated by Django 5.2.8 on 2026-06-03 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_studygroup_has_coding_portal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Data Structures', max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('accuracy', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField(default=0)),
                ('elo_rating', models.FloatField(default=1200.0)),
                ('last_practiced', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject', 'topic')},
            },
        ),
    ]
