# Generated by Django 5.2.8 on 2026-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_usertopicmastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='boilerplate_code',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='hidden_test_cases',
            field=models.JSONField(default=list),
        ),
    ]
