# Generated by Django 5.2.8 on 2026-06-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_question_boilerplate_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='has_coding_portal',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='active_portals',
            field=models.ManyToManyField(blank=True, related_name='subscribed_groups', to='groups.codingportal'),
        ),
        migrations.AddField(
            model_name='topic',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='groups.codingportal'),
        ),
    ]
