# Generated by Django 5.2.8 on 2026-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_codingportal_remove_studygroup_has_coding_portal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hidden_wrapper_code',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
