# Generated by Django 5.2.8 on 2026-06-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercodingprofile',
            name='irt_latent_ability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usertopicmastery',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='usertopicmastery',
            name='sm2_interval',
            field=models.IntegerField(default=0),
        ),
    ]
