# Generated by Django 5.2.8 on 2026-06-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_usercodingprofile_irt_latent_ability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenticCoachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=100)),
                ('failed_attempts_count', models.IntegerField(default=3)),
                ('generated_hint', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('webhook_fired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
