# Generated by Django 5.2.8 on 2026-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_recommendationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercodingprofile',
            old_name='irt_latent_ability',
            new_name='irt_latent_logic',
        ),
        migrations.RemoveField(
            model_name='usertopicmastery',
            name='easiness_factor',
        ),
        migrations.RemoveField(
            model_name='usertopicmastery',
            name='sm2_interval',
        ),
        migrations.AddField(
            model_name='usercodingprofile',
            name='irt_latent_optimization',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usercodingprofile',
            name='irt_latent_syntax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usertopicmastery',
            name='hlr_alpha',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='usertopicmastery',
            name='hlr_halflife',
            field=models.FloatField(default=1.0),
        ),
    ]
