# Generated by Django 5.2.8 on 2026-06-27 08:32

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_badge_usercodingprofile_current_streak_and_more'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.AlterField(
            model_name='document',
            name='feature_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
